using System.Collections;
using System.Collections.Generic;
using UnityEngine;


// Validate a map generated by simple tiled wfc
public class ValidateMap : MonoBehaviour
{
    
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
